version = 0.1

[default.deploy.parameters]
stack_name = "chmura-baza-150"
resolve_s3 = true
s3_prefix = "chmura-baza-150"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
